export const keys = [
    { value: 'AC', category: 'RESET', classes: 'darkgray_color'},
    { value: '+/-', category: 'UNIACTION', classes: 'darkgray_color'},
    { value: '%', category: 'UNIACTION', classes: 'darkgray_color'},
    { value: '÷', category: 'OPERATOR', classes: 'orange_color'},
    { value: '7', category: 'NUMBER', classes: 'gray_color'},
    { value: '8', category: 'NUMBER',  classes: 'gray_color'},
    { value: '9', category: 'NUMBER', classes: 'gray_color'},
    { value: 'x', category: 'OPERATOR', classes: 'orange_color'},
    { value: '4', category: 'NUMBER',  classes: 'gray_color'},
    { value: '5', category: 'NUMBER',  classes: 'gray_color'},
    { value: '6', category: 'NUMBER', classes: 'gray_color'},
    { value: '-', category: 'OPERATOR', classes: 'orange_color'},
    { value: '1', category: 'NUMBER', classes: 'gray_color'},
    { value: '2', category: 'NUMBER', classes: 'gray_color'},
    { value: '3', category: 'NUMBER', classes: 'gray_color'},
    { value: '+', category: 'OPERATOR', classes: 'orange_color'},
    { value: '0', category: 'NUMBER', classes: 'double gray_color border_bottom_left'},
    { value: '.', category: 'UNIACTION', classes: 'gray_color'},
    { value: '=', category: 'OPERATOR', classes: 'orange_color border_bottom_right'},
]
